---
title: "Making Working Adapter Dilutions"
params:
  initial_conc_uM: 200
  working_conc_uM: 10
  final_vol_ul: 100
  adpater_stock: "r_p2_primer_illumina_index_stock_ul"
---
```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```


This recipe is the same for ddRADSeq and EecSeq protocols
```{r working, echo=FALSE}
working_guide <- tribble(~item, ~initial_conc, ~final_conc, 
                   params$adpater_stock, params$initial_conc_uM, params$working_conc_uM,
                   "ph2o_ul", 0, 0) %>% 
  mutate(final_vol_ul = params$final_vol_ul,
         initial_vol_ul = final_conc * final_vol_ul/initial_conc,
         initial_vol_ul = ifelse(item == "ph2o_ul",final_vol_ul - sum(initial_vol_ul, na.rm = T), initial_vol_ul))
 
working <- working_guide %>% 
  select(item, initial_vol_ul) %>% 
  rename(quantity = initial_vol_ul) %>% 
  mutate(item = ifelse(item == "ph2o_ul", "ph2o_ml", item), 
         quantity = ifelse(item == "ph2o_ml", quantity/1000, quantity)) %>% 
  bind_rows(tribble(~item, ~quantity,
                    "tips_10", 1,
                    "tips_100", 1,
                    "tubes_1.7ml", 1))
         
kable(working_guide) %>%
  kable_styling("bordered") %>%
  add_header_above(c("working stock solution" = 5))
```
```{r}
rm(working_guide)
```

