---
title: "Hybridization Stock Solution for Ali Extraction"
params:
  final_vol_ul: 50000
---
```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r hybrid, echo=FALSE}
hybrid_guide <- tribble(~item, ~initial_conc, ~final_conc, 
                   "4.45_M_NaCl_ul", 4.45, 2.5,
                   "50_perc_peg_8000", 50, 20,
                   "1000_mM_DTT_ul", 1000, 25,
                   "ph2o_ul", 0, 0 ) %>% 
  mutate(final_vol_ul = params$final_vol_ul,
    initial_vol_ul = final_conc* final_vol_ul/initial_conc,
         initial_vol_ul = ifelse(item == "ph2o_ul",final_vol_ul - sum(initial_vol_ul, na.rm = T), initial_vol_ul))


hybrid <- hybrid_guide %>% 
  select(item, initial_vol_ul) %>% 
  rename(quantity = initial_vol_ul) %>% 
  mutate(item = ifelse(item == "ph2o_ul", "ph2o_ml", item), 
         quantity = ifelse(item == "ph2o_ml", quantity/1000, quantity))
         
kable(hybrid_guide) %>%
  kable_styling("bordered") %>%
  add_header_above(c("hybrid stock solution" = 5))
```


```{r}
rm(hybrid_guide)
```
