---
title: "Liftons Stock Solution"
params:
  final_vol_ul: 50000
---
```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r liftons, echo=FALSE}
liftons_guide <- tribble(~item, ~initial_conc, ~final_conc, 
                   "500_mM_edta_ul", 500, 100,
                   "1000_mM_Tris-HCl_pH7.5_ul", 1000, 25,
                   "10_perc_sds_ul", 10, 1,
                   "ph2o_ul", 0, 0 ) %>% 
  mutate(final_vol_ul = params$final_vol_ul,
    initial_vol_ul = final_conc* final_vol_ul/initial_conc,
         initial_vol_ul = ifelse(item == "ph2o_ul",final_vol_ul - sum(initial_vol_ul, na.rm = T), initial_vol_ul))
 
liftons <- liftons_guide %>% 
  select(item, initial_vol_ul) %>% 
  rename(quantity = initial_vol_ul) %>% 
  mutate(item = ifelse(item == "ph2o_ul", "ph2o_ml", item), 
         quantity = ifelse(item == "ph2o_ml", quantity/1000, quantity))
         
kable(liftons_guide) %>%
  kable_styling("bordered") %>%
  add_header_above(c("liftons stock solution" = 5))
```


```{r}
rm(liftons_guide)
```
