---
title: "TE stock solution"
params:
  initial_conc: 20
  final_conc: 1
  final_vol_ul: 15000
---
```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r}
low_te_guide <- tribble(~item, ~initial_conc, ~final_conc,
                        "1000_mM_Tris-HCl_pH7.5_ul", 1000, 10, 
                        "500_mM_edta_ul", 500, 0.1, 
                        "ph2o_ul", 0, 0) %>% 
  mutate(final_vol_ul = params$final_vol_ul,
         initial_vol_ul = final_conc* final_vol_ul/initial_conc,
         initial_vol_ul = ifelse(item == "ph2o_ul",final_vol_ul - sum(initial_vol_ul, na.rm = T), initial_vol_ul))

low_te <- low_te_guide %>% 
  select(item, initial_vol_ul) %>% 
  rename(quantity = initial_vol_ul) %>% 
  mutate(item = ifelse(item == "ph2o_ul", "ph2o_ml", item), 
         quantity = ifelse(item == "ph2o_ml", quantity/1000, quantity))

kable(low_te_guide) %>%
  kable_styling() %>%
  add_header_above(c("Low TE buffer" = 5))
```

```{r}
rm(low_te_guide)
```

