---
title: "TE stock solution"
params:
  initial_conc: 20
  final_conc: 1
  final_vol_ul: 500000
---
```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
options(scipen = 999)
```

## Prepare a stock solution of TE buffer
- Normally, the pico kit sends a 25mL bottle of 20x TE that can be dumped into a 500 mL flask and filled to the 500 line with distilled water from the special tap.
```{r edta, echo=FALSE}

te <- tribble(~item, ~quantity,
                      "1x_te_buffer_ul", (params$final_vol_ul*params$final_conc)/params$initial_conc)
```

## TE can also be made in the lab with Tris-HCl and EDTA.
- this recipe is from IDT
```{r}
te_guide <- tribble(~item, ~initial_conc, ~final_conc, 
                   "500_mM_edta_ul", 500,100,
                   "1000_mM_Tris-HCl_pH8_ul", 1000,10,
                   "dh2o_ul", 0, 0 ) %>% 
  mutate(final_vol_uL = params$final_vol_ul,
    initial_vol_uL = final_conc* final_vol_uL/initial_conc,
         initial_vol_uL = ifelse(item == "dh2o_ul",final_vol_uL - sum(initial_vol_uL, na.rm = T), initial_vol_uL))
```
Adjust pH with HCl or NaOH
