---
title: "10mM Tris 0.05 Tween Stock"
params:
  final_vol_ul: 1500
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
```

```{r tris_tween, echo=FALSE}
tris_tween_guide <- tribble(~item, ~initial_conc, ~final_conc, 
                   "1000_mM_Tris-HCl_pH8_ul", 1000,10,
                   "100_perc_tween_20_ul", 100, 0.05,
                   "ph2o_ul", 0, 0 ) %>% 
  mutate(final_vol_uL = params$final_vol_ul,
    initial_vol_uL = final_conc* final_vol_uL/initial_conc,
         initial_vol_uL = ifelse(item == "ph2o_ul",final_vol_uL - sum(initial_vol_uL, na.rm = T), initial_vol_uL))
 
tris_tween <- tris_tween_guide %>% 
  select(item, initial_vol_uL) %>% 
  rename(quantity = initial_vol_uL) %>% 
  mutate(item = ifelse(item == "ph2o_ul", "ph2o_ml", item), 
         quantity = ifelse(item == "ph2o_ml", quantity/1000, quantity))
         
kable(tris_tween_guide) %>%
  kable_styling("bordered") %>%
  add_header_above(c("tris_tween stock solution" = 5))
```
```{r}
rm(tris_tween_guide)
```

