---
title: "ddRADSeq Library Prep"
output: github_document
always_allow_html: yes
---
<!-- http://www.nagraj.net/notes/multiple-rmarkdown-reports/ will read in a bunch of data files, but not rmds-->
<!-- https://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output parents and children -->
<!-- https://stackoverflow.com/questions/49475303/rmarkdown-child-documents-do-not-detect-their-params -->
## Sample provenance
Some of our methods have changed over time.  Here is a very simplified breakdown of which protocols were used with which samples.
```{r echo=FALSE}
kableExtra::kable_styling(
knitr::kable(
readr::read_csv("field season, extraction method, ligation setup, baits
          2012, Qiagen DNeasy 96, no robot, no baits
          2013, Qiagen DNeasy 96, no robot, no baits
          2014, Qiagen DNeasy 96, no robot, no baits
          2015, Qiagen DNeasy 96, no robot and robot, no baits
          2016, Ali, robot, baits
          2017, Ali, robot, baits
          2018, Ali, robot, baits")
)
)


```

**WARNING: These protocols are abridged versions of the manufacturers recommended protocols.  Use of these protocols assumes familiarity with manufacutrers instructions.  Please read manufacturers instructions if this is your first time (or first time in a while) performing these procedures.**

## DNA Library Preparation
[1. DNA Extraction](https://pinskylab.github.io/laboratory/protocols/dna_extraction_ali.nb.html)  
[2. Quantify](https://pinskylab.github.io/laboratory/protocols/quant_dna.nb.html)  
[3. Digest](https://pinskylab.github.io/laboratory/protocols/digest_dna.nb.html)  
[4. Clean](https://pinskylab.github.io/laboratory/protocols/ampure.nb.html)  
[5. Quantify](https://pinskylab.github.io/laboratory/protocols/quant_dna.nb.html)  
[Anneal?](https://pinskylab.github.io/laboratory/protocols/anneal.html)  
- If adapters, oligos, or primers need to be rehydrated, it should be done the day before they are needed.  This is a good place to check supplies and make sure you have plenty of working stock of the oligos.  

[6. Robot](https://pinskylab.github.io/laboratory/protocols/robot.html)  
[7. Ligate DNA](https://pinskylab.github.io/laboratory/protocols/ligation_ddradseq.nb.html)  
[8. Pool](https://pinskylab.github.io/laboratory/protocols/pool.nb.html)  
[9. Clean 1](https://pinskylab.github.io/laboratory/protocols/ampure.nb.html)  
- Break up pools into 4 vials of 250ul each, use 375ul ampure for each vial.  
[10. Clean 2](https://pinskylab.github.io/laboratory/protocols/ampure.nb.html)  
- use 40ul of sample and 60ul of ampure.  
[11. Size Select](https://pinskylab.github.io/laboratory/protocols/pippin.nb.html)  
[12. PCR](https://pinskylab.github.io/laboratory/protocols/lib-amp_eecseq.nb.html)  
[13. Baits](https://pinskylab.github.io/laboratory/protocols/baits.nb.html)  
[14. Sequencing Prep]((https://pinskylab.github.io/laboratory/protocols/seq-prep_ddradseq.nb.html)  )
