#!/bin/bash
mv /local/home/michelles/02-apcl-ddocent/17seq/samples/APCL_L3119* /local/home/michelles/02-apcl-ddocent/17seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3589* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/12seq/samples/APCL_L2324* /local/home/michelles/02-apcl-ddocent/12seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3400* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/03seq/samples/APCL_L0306* /local/home/michelles/02-apcl-ddocent/03seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3598* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/03seq/samples/APCL_L0308* /local/home/michelles/02-apcl-ddocent/03seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3599* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/03seq/samples/APCL_L0309* /local/home/michelles/02-apcl-ddocent/03seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3601* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/08seq/samples/APCL_L1188* /local/home/michelles/02-apcl-ddocent/08seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3266* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3352* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2513* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3600* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/08seq/samples/APCL_L1297* /local/home/michelles/02-apcl-ddocent/08seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3596* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/12seq/samples/APCL_L2351* /local/home/michelles/02-apcl-ddocent/12seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3604* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2502* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3595* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2514* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3594* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2503* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3593* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2515* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3592* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2516* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3591* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2504* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3626* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/13seq/samples/APCL_L2505* /local/home/michelles/02-apcl-ddocent/13seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3633* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/17seq/samples/APCL_L3170* /local/home/michelles/02-apcl-ddocent/17seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3643* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/04seq/samples/APCL_L0814* /local/home/michelles/02-apcl-ddocent/04seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3644* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/17seq/samples/APCL_L3106* /local/home/michelles/02-apcl-ddocent/17seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3597* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/17seq/samples/APCL_L3152* /local/home/michelles/02-apcl-ddocent/17seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3588* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/17seq/samples/APCL_L3146* /local/home/michelles/02-apcl-ddocent/17seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3602* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3264* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3436* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3263* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3437* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3260* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3438* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3254* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3439* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3253* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3440* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3247* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3441* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3246* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3442* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3244* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3443* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3243* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3444* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3242* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3445* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3241* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3446* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/28seq/samples/APCL_L3240* /local/home/michelles/02-apcl-ddocent/28seq/samples/regenos/
mv /local/home/michelles/02-apcl-ddocent/30seq/samples/APCL_L3447* /local/home/michelles/02-apcl-ddocent/30seq/samples/regenos/
